CREATE TABLE ORDERS(
ID NUMBER,
CONSTRAINT ORDER_ID PRIMARY KEY (ID),
CONSTRAINT ORDER_ID_NUMBER CHECK (ID<=10000),
USER_ID NUMBER UNIQUE,
ROOM_ID NUMBER UNIQUE,
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID NUMERIC (8,2)
);